// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetCachedRepositories():Promise<Array<models.Repository>>;

export function GetRepositoryByID(arg1:string,arg2:string):Promise<models.Repository>;

export function GetTrendingRepositories(arg1:string,arg2:string):Promise<Array<models.Repository>>;

export function Greet(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function RefreshRepositories():Promise<Array<models.Repository>>;

export function Shutdown(arg1:context.Context):Promise<void>;
