// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {backend} from '../models';

export function GetCachedRepositories():Promise<Array<models.Repository>>;

export function GetCurrentUser():Promise<models.User>;

export function GetLoginMethod():Promise<string>;

export function GetRepositoryByID(arg1:string,arg2:string):Promise<models.Repository>;

export function GetStarredRepositories():Promise<Array<models.Repository>>;

export function GetTrendingRepositories(arg1:string,arg2:string):Promise<Array<models.Repository>>;

export function GetUserRepositories():Promise<Array<models.Repository>>;

export function Greet(arg1:string):Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Logout():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenVerificationURL():Promise<void>;

export function RefreshRepositories():Promise<Array<models.Repository>>;

export function SetGitHubConfig(arg1:string,arg2:string):Promise<void>;

export function SetLoginMethod(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartDeviceFlowLogin():Promise<backend.DeviceFlowInfo>;

export function StartLogin():Promise<string>;
