// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceRefreshUserStarRepo() {
  return window['go']['backend']['App']['ForceRefreshUserStarRepo']();
}

export function GetCurrentUser() {
  return window['go']['backend']['App']['GetCurrentUser']();
}

export function GetLoginMethod() {
  return window['go']['backend']['App']['GetLoginMethod']();
}

export function GetLogs() {
  return window['go']['backend']['App']['GetLogs']();
}

export function GetRepositoryByID(arg1, arg2) {
  return window['go']['backend']['App']['GetRepositoryByID'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function GetStarredRepositories() {
  return window['go']['backend']['App']['GetStarredRepositories']();
}

export function GetTrendingRepositories(arg1) {
  return window['go']['backend']['App']['GetTrendingRepositories'](arg1);
}

export function GetUserRepositories() {
  return window['go']['backend']['App']['GetUserRepositories']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function IsLoggedIn() {
  return window['go']['backend']['App']['IsLoggedIn']();
}

export function LoadTrendingData() {
  return window['go']['backend']['App']['LoadTrendingData']();
}

export function LoadUserStarRepo() {
  return window['go']['backend']['App']['LoadUserStarRepo']();
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function OpenDirectoryDialog() {
  return window['go']['backend']['App']['OpenDirectoryDialog']();
}

export function OpenURL(arg1) {
  return window['go']['backend']['App']['OpenURL'](arg1);
}

export function OpenVerificationURL() {
  return window['go']['backend']['App']['OpenVerificationURL']();
}

export function RefreshTrending() {
  return window['go']['backend']['App']['RefreshTrending']();
}

export function RefreshUserStarRepo() {
  return window['go']['backend']['App']['RefreshUserStarRepo']();
}

export function SetGitHubConfig(arg1, arg2) {
  return window['go']['backend']['App']['SetGitHubConfig'](arg1, arg2);
}

export function SetLoginMethod(arg1) {
  return window['go']['backend']['App']['SetLoginMethod'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function StartDeviceFlowLogin() {
  return window['go']['backend']['App']['StartDeviceFlowLogin']();
}

export function StartLogin() {
  return window['go']['backend']['App']['StartLogin']();
}

export function UpdateSettings(arg1) {
  return window['go']['backend']['App']['UpdateSettings'](arg1);
}
