// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCachedRepositories() {
  return window['go']['backend']['App']['GetCachedRepositories']();
}

export function GetRepositoryByID(arg1, arg2) {
  return window['go']['backend']['App']['GetRepositoryByID'](arg1, arg2);
}

export function GetTrendingRepositories(arg1, arg2) {
  return window['go']['backend']['App']['GetTrendingRepositories'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['backend']['App']['OpenURL'](arg1);
}

export function RefreshRepositories() {
  return window['go']['backend']['App']['RefreshRepositories']();
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}
